### ISSUE TITLE
ImportError: cannot import name 'main'

### ISSUE THREAD

**Issue by frankmuc** [dfd-tud/deda#10] opened 2018-07-15 16:00 UTC
I installed DeDa on different platforms but wherever I am running a command, it returns an error:

ImportError: cannot import name 'main'

Command (example):

deda_clean_document test.tif

deda was installed via pip3 install deda and all components were downloaded and installed. Everything was successful, but I just can't run any of the commands.

Last attempt was OpenSuSE an pip 10.0.1.

**Comment by frankmuc** [comment] 2018-07-15 16:20
(base) C:\Users\Frank_PC>deda_clean_document test.png
Traceback (most recent call last):
  File "d:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\Scripts\deda_clean_document.exe\__main__.py", line 5, in <module>
ImportError: cannot import name 'main'

**Comment by jmgurney** [comment] 2018-07-15 23:54
Able to reproduce as well.  Temporary work around is:
```
$python -m bin.deda_parse_print
usage: deda_parse_print.py [-h] [-m MASK] [-d DPI] [-o] [-v] file
deda_parse_print.py: error: the following arguments are required: file
```

Looks like the Main symbol in deda_parse_print changed to Main and a slightly different calling convention.

**Comment by timojuez** [comment] 2018-07-16 09:18
Thank you. Fixed in version 1.0b3.
$ pip3 install --upgrade deda

**Closed as completed by timojuez** 2018-07-16 09:18 UTC

**Comment by frankmuc** [comment] 2018-07-16 15:33
On Windows using Anaconda, I still have the same problem regarding "cannot import main". But the workaround "python -m bin.deda_parse_print" appears to work. Linux has not been tested yet because I need to start my ESXi.

**Comment by timojuez** [comment] 2018-07-16 15:39
Please uninstall the old version.
$ pip uninstall deda
And check if deda_parse_print cannot be found.
Are you on Deda version 1.0b3 when you reinstall?

**Comment by frankmuc** [comment] 2018-07-16 15:51
I uninstalled and reinstalled (but it was already 1.0b3). Now I can no longer run deda_parse_print from the command line which worked previously:

>deda_parse_print
Command not found

but this works:

>python -m bin.deda_parse_print

usage: deda_parse_print.py [-h] [-m MASK] [-d DPI] [-o] [-v] file
deda_parse_print.py: error: the following arguments are required: file

The files in the Anaconda3\Scripts folder are now python text files without a file extension. Weren't these .exe files previously?

**Comment by timojuez** [comment] 2018-07-17 07:50
Hi Frank,

the mentioned error is platform dependent unfortunately. But this has been fixed in the development branch and will work in the next release.
Unix-style systems shall now be able to run the program. The Angloamerican OS indeed needs file extensions. Maybe for now add "python" to the call like
$ python deda_parse_print #or 
$ python Anaconda3\Scripts\deda_parse_print


Best wishes to München
